#!/usr/bin/env bash
# Install the `marky` CLI as a wrapper that launches the GUI detached
# from the calling terminal, then returns immediately.
#
# Run after `pnpm tauri build` (preferred — installs the .app bundle)
# or after `pnpm tauri build --no-bundle` (raw binary fallback).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET_DIR="${MARKY_INSTALL_DIR:-$HOME/.local/bin}"
WRAPPER="$TARGET_DIR/marky"

APP_BUNDLE="$ROOT/src-tauri/target/release/bundle/macos/Marky.app"
RAW_BINARY="$ROOT/src-tauri/target/release/marky"
DEBUG_BINARY="$ROOT/src-tauri/target/debug/marky"

mkdir -p "$TARGET_DIR"

if [[ -d "$APP_BUNDLE" ]]; then
  BINARY="$APP_BUNDLE/Contents/MacOS/marky"
  # macOS bundle: direct-exec the inner binary so tauri-plugin-single-instance
  # can detect the lock and forward args to an already-running instance.
  # `open -a` routes through Apple Events which bypasses single_instance entirely.
  # Paths must be resolved to absolute because the binary may have a different cwd.
  cat > "$WRAPPER" <<'OUTER'
#!/usr/bin/env bash
# Auto-generated by marky/scripts/install-cli.sh
args=()
for arg in "$@"; do
  if [[ "$arg" != -* ]]; then
    if [[ -d "$arg" ]]; then
      args+=("$(cd "$arg" && pwd)")
    elif [[ -f "$arg" ]]; then
      args+=("$(cd "$(dirname "$arg")" && pwd)/$(basename "$arg")")
    else
      args+=("$arg")
    fi
  else
    args+=("$arg")
  fi
done
OUTER
  # Inject the resolved binary path — nohup + disown so the shell returns immediately
  cat >> "$WRAPPER" <<EOF
nohup "$BINARY" "\${args[@]}" >/dev/null 2>&1 &
disown >/dev/null 2>&1 || true
EOF
  source_kind="bundle ($APP_BUNDLE)"
elif [[ -x "$RAW_BINARY" || -x "$DEBUG_BINARY" ]]; then
  bin="$RAW_BINARY"
  [[ -x "$bin" ]] || bin="$DEBUG_BINARY"
  # Raw binary: spawn detached, redirect output, disown.
  cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by marky/scripts/install-cli.sh
nohup "$bin" "\$@" >/dev/null 2>&1 &
disown >/dev/null 2>&1 || true
EOF
  source_kind="binary ($bin)"
else
  echo "error: no built marky binary found." >&2
  echo "  build first with:  pnpm tauri build" >&2
  exit 1
fi

chmod +x "$WRAPPER"
echo "installed wrapper: $WRAPPER"
echo "  → $source_kind"

case ":$PATH:" in
  *":$TARGET_DIR:"*)
    echo "ready: run 'marky FILE.md' or 'marky DIR/'"
    ;;
  *)
    echo
    echo "warning: $TARGET_DIR is not on PATH"
    echo "  add this to your shell profile:"
    echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo "  or for fish:"
    echo "    set -Ux fish_user_paths \$HOME/.local/bin \$fish_user_paths"
    ;;
esac
